### PR TITLE
Sorted stories by kind

### PR DESCRIPTION
**Pull request by thzinc**
I really love Storybook and am leading a team that uses it. We've got a lot of stories in the list that would be much easier to look at if they were sorted. I think my addition to the filter function is the right place for this, but I'm open to feedback.

### CODE REVIEW

**Comment by arunoda** [comment]
This will break things. So, I'd like to do this as an option.
Use can set an option here: https://github.com/storybooks/storybook-addon-options

Then we do this if so.

**Comment by thzinc** [comment]
@arunoda, I will review `storybook-addon-options` and close this PR. Thanks for the feedback!

**Comment by arunoda** [comment]
Actually, you can simply continue this PR and provide an option via https://github.com/storybooks/storybook-addon-options

I just don't want this to be the default behaviour.

**Comment by thzinc** [comment]
Ah, ok. Will do!

**Comment by thzinc** [comment]
I've updated my PR to use a new `sortStoriesByKind` boolean option. The default behavior is to pass the stories along, unsorted and unmutated. Only if the option is `true`, the stories will be sorted by the `kind` property.

**Comment by arunoda** [comment]
This is great. Thanks.
Could you send a new PR to https://github.com/storybooks/storybook-addon-options updating the README.

**Comment by thzinc** [comment]
Absolutely!

**Pull request merged**
