### PR TITLE
windows support for prepublish script

### PR DESCRIPTION
**Pull request by UsulPro**
Makes life of windows contributors a bit easier :)

### CODE REVIEW

**Comment by ndelangen** [comment]
Does `#!/bin/bash` not work on windows?

**Comment by UsulPro** [comment]
Unfortunately no
I always need to change it manually before making distrib

**Comment by UsulPro** [comment]
@ndelangen do you think we can cause some inconvenience merging this?

**Comment by mnmtanish** [comment]
I think it's better if we can write the prepublish script with [shelljs](https://github.com/shelljs/shelljs) and call it like `node .scripts/prepublish.js`.

**Comment by UsulPro** [comment]
@mnmtanish such scripts already done actually :)
https://github.com/sm-react/react-theming/blob/master/.scripts/npm-prepublish.js
I'll create another PR then

**Pull request closed without merging**
